volumes: 
  postgres_data:

services:
  postgres:
    build: .
    image: postgresql_local
    hostname: postgresql_local
    networks:
      - net_swarm
    environment:
      POSTGRES_PASSWORD: postgresql
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 256M
      restart_policy:
        condition: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 10s
      
networks:
  net_swarm:
    external: true
    name: net_swarm